### ISSUE TITLE
Documentation (or bugfix?) with respect to the `COURT_LENGTH` specification

### ISSUE THREAD

**Issue by mikewojnowicz** [airalcorn2/baller2vec#5]
Dear Michael, 

Thank you for your very interesting work!

My issue is as follows.  The [`COURT_LENGTH` variable](https://github.com/airalcorn2/baller2vec/blob/master/settings.py#L17) is defined to be 94, which differs from the [`X_MAX` variable](https://github.com/airalcorn2/baller2vec/blob/master/settings.py#L8), defined to be 100.  

I am a bit puzzled by this discrepancy.   I would have expected `COURT_LENGTH`=`X_MAX`=100.  Indeed, on the other dimension of the court, we do have `COURT_WIDTH`=`Y_MAX` .

Is it possible to provide documentation (or at least to provide a quick answer here in the issues) as to what motivated the choice of `94` when defining `COURT_LENGTH`? 

Although the `COURT_LENGTH` is defined in the settings file, and therefore might seem to be arbitrarily specifiable, it does have an effect on the [court rotations](https://github.com/airalcorn2/baller2vec/blob/master/baller2vec_dataset.py#L124).  So, for instance, if some player's observed `x` coordinate at a timestep is `99` (which does seem to happen in the data), then the rotated value would be `-5`, which seems weird since a typical min `x` coordinate before rotation (or, more precisely, the min value from one game I looked at for TOR vs CHA) is only about `-1`.

**Comment by airalcorn2** [comment]
[The dimensions of an NBA court are 94 feet by 50 feet.](https://en.wikipedia.org/wiki/Basketball_court) `X_MAX` and `Y_MAX` [are only used for plotting](https://github.com/search?q=repo%3Aairalcorn2%2Fballer2vec%20X_MAX&type=code) and were inherited from [the dataset repo](https://github.com/linouk23/NBA-Player-Movements/blob/master/Constant.py). Having a larger plotting area than the size of the court allows players to be shown out of bounds (which is why you see values like 99 in the data). The rotated value for 99 is indeed -5 as you recognized, which corresponds to being five feet out of bounds, i.e., pretty far, and most likely why you only saw a minimum x value of -1 in the game you checked.

**Comment by mikewojnowicz** [comment]
Thank you.  That makes sense, and almost completely resolves my confusion.  My only remaining question is this - if the court width is given by the interval [0,94], and then one wants to pad this interval to allow for players going out of bounds, why is the resulting interval specified by [0,100] rather than [-6,100]?

**Comment by airalcorn2** [comment]
You're right that that the plotting area should probably have an x range of [-6, 100]. That bit of code was likewise [inherited from the original dataset repo](https://github.com/linouk23/NBA-Player-Movements/blob/f7d4cf2c7e607029abfd5715a0d4073bedae328e/Event.py#L42). You can actually see an artifact of this setting in the GIF in [this section of the README](https://github.com/airalcorn2/baller2vec#animating-a-sequence). The players "snap" to the sideline when they start going out of bounds.
